"""add document types and requirements

Revision ID: 78d01d236532
Revises: 36d35368b8a7
Create Date: 2026-07-26 15:34:09.323819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d01d236532'
down_revision: Union[str, Sequence[str], None] = '36d35368b8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type_id', 'employment_type', name='uq_document_requirement_type_employment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_requirements')
    op.drop_table('document_types')
    # ### end Alembic commands ###
